### ISSUE TITLE
Activity back Stack issue

### ISSUE THREAD

**Issue by gauravagerwala** [aneesh-neelam/VITacademics-Android#1]
Back button needs to be clicked twice to exit MainActivity
For now, LoginActivity is the launcher. Can be changed once api work is done

**Comment by aneesh-neelam** [comment]
As long as it is only temporary, it's fine.

**Comment by gauravagerwala** [comment]
This might be a reason. The app still runs but the log throws this warning

06-15 18:48:15.722  15667-15667/com.karthikb351.vitinfo2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:417)
            at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:452)
            at com.karthikb351.vitinfo2.activity.MainActivity$1.onItemClick(MainActivity.java:117)
            at android.widget.AdapterView.performItemClick(AdapterView.java:292)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1394)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3024)
            at android.widget.AbsListView$1.run(AbsListView.java:3830)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4517)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by aneesh-neelam** [comment]
Hey, whenever I try to open your Fragments the app crashes. This is the current `rewrite` branch, what you guys did before I merged it the first time.

**Comment by gauravagerwala** [comment]
Yes. That has been fixed in the current ui branch. Run from there for now

**Comment by aneesh-neelam** [comment]
Yes, each Fragment is placed in the back stack, which isn't supposed to happen. Any progress on this?

**Comment by gauravagerwala** [comment]
Its been fixed.
